### ISSUE TITLE
Web Pages and GitHub Pages Outdated since 2022-10-20

### ISSUE THREAD

**Issue by bc-lee** [w3c/mediacapture-transform#110]
Both the Specification and Editor's Draft web pages haven't been updated since 2022-10-20.

* [https://www.w3.org/TR/mediacapture-streams/](https://www.w3.org/TR/mediacapture-streams/)
* [https://github.com/w3c/mediacapture-fromelement](https://github.com/w3c/mediacapture-fromelement)

Additionally, the [gh-pages](https://github.com/w3c/mediacapture-transform/tree/gh-pages) branch on the GitHub repository hasn't been updated since the same date.

It appears that the GitHub Action [.github/workflows/auto-publish.yml](https://github.com/w3c/mediacapture-transform/blob/main/.github/workflows/auto-publish.yml) has never succeeded. The issue may be related to the commit efec34bafb8a0f2955a8bf8666386419dde4fc35. This commit updated the workflow configuration but appears to have an error.

The first few lines of the file define the workflow trigger:
```yaml
name: Auto-publish
on:
  pull_request: {}
  paths: index.bs
  push:
    branches: [main]
```

The `paths` element within the top-level `on` section is not supported. The intended behavior seems to be triggering the workflow when the `index.bs` file is updated.

To correct the trigger configuration, use the `paths` element within the `on.push` section:

```yaml
name: Auto-publish
on:
  pull_request:
    branches: [main]
    paths:
      - 'index.bs'
  push:
    branches: [main]
    paths:
      - 'index.bs'
```

( https://github.com/w3c/spec-prod/blob/796e4101600225fe24d1e967416e348fefdcc266/docs/examples.md#multiple-specs-in-same-repository has more examples to use `paths` element in `on` element. )

Also, I wonder if such a filtering is necessary. It seems other files may affect the generated web pages. If the intention is to update the web pages when any file is updated, the correct way is to remove `paths` element from `on` element.
